#!/usr/bin/python3

print("Content-Type: text/html\r")
print("\r")
print("<!DOCTYPE html>")
print("<html>")
print("<head>")
print("    <title>CGI Test Script</title>")
print("    <style>")
print("        body { font-family: Arial, sans-serif; margin: 40px; }")
print("        .container { max-width: 600px; margin: 0 auto; }")
print("        h1 { color: #2c3e50; }")
print("        .success { color: #27ae60; font-weight: bold; }")
print("        .info { background: #ecf0f1; padding: 15px; border-radius: 5px; }")
print("    </style>")
print("</head>")
print("<body>")
print("    <div class='container'>")
print("        <h1>🐍 CGI Test Script</h1>")
print("        <p class='success'>✅ CGI script executed successfully!</p>")
print("        <div class='info'>")
print("            <h3>Script Information:</h3>")
print("            <ul>")
print("                <li><strong>Script:</strong> test.py</li>")
print("                <li><strong>Interpreter:</strong> Python 3</li>")
print("                <li><strong>Location:</strong> /cgi-bin/</li>")
print("            </ul>")
print("        </div>")
print("        <p>This demonstrates that your webserv can execute CGI scripts.</p>")
print("        <a href='/'>← Back to Home</a>")
print("    </div>")
print("</body>")
print("</html>")
